name: flutter_super_log_manager
description: "A comprehensive Flutter debug logging plugin with overlay bubble, error catching, and advanced log viewer. Supports RTL/LTR, custom navigation, and performance optimizations."
version: 1.0.1
homepage: https://pub.dev/packages/flutter_super_log_manager
repository: https://github.com/a7mdragab1/flutter_super_log_manager
issue_tracker: https://github.com/a7mdragab1/flutter_super_log_manager/issues
documentation: https://pub.dev/packages/flutter_super_log_manager

environment:
  sdk: ^3.10.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

topics:
  - logging
  - debug
  - overlay
  - error-handling

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  assets:
    - screenshots/
